import './globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOption } from "@/utility/auth";
import Navbar from '@/component/nav/Navbar';
import { Provider } from './Providers';
import { CustomSession } from '@/utility/CustomSession';

export const metadata: Metadata = {
  title: 'GupSup',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch session
  const session = await getServerSession(authOption);

 

  let sesion: CustomSession;

  if (session) {
    const user = {
      name: session.user.name,
      url: session.user.image || '',
      email: session.user.email,
      about: session.user.about || null,
      role: session.user.role,
      id: session.user.id.toString(), // `id` as mongoose.Types.ObjectId
    };
    sesion = { user };
  } else {
    sesion = { user: null };
  }

  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar sesion={sesion} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
