import { Suspense } from 'react'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'write',
  description: 'Generated by create next app',
}


export default function TestLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
      
       
        {children}
      
       
      </>
    )
  }
  